# Generated by Django 4.2.9 on 2024-05-08 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('presentation_video', models.FileField(blank=True, null=True, upload_to='presentation_videos/', verbose_name='video de présentation')),
                ('is_visible', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'catégorie',
                'verbose_name_plural': 'catégories',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveIntegerField(default=0, verbose_name='ordering')),
                ('name', models.CharField(max_length=500, verbose_name='nom')),
                ('video', models.FileField(upload_to='videos/')),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('presentation_video', models.FileField(blank=True, null=True, upload_to='presentation_resume_video/', verbose_name='video de présentation')),
                ('categories', models.ManyToManyField(related_name='videos', to='videos.category')),
                ('directors', models.ManyToManyField(related_name='videos', to=settings.AUTH_USER_MODEL, verbose_name='réalisateurs')),
            ],
            options={
                'verbose_name': 'vidéo',
                'verbose_name_plural': 'vidéos',
                'ordering': ['ordering'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveIntegerField(default=0, verbose_name='ordering')),
                ('screenshot', models.ImageField(upload_to='screenshot')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='videos.video')),
            ],
            options={
                'ordering': ['ordering'],
                'abstract': False,
            },
        ),
    ]
