"""
Django settings for web project.

Generated by 'django-admin startproject' using Django 4.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from email.policy import default
from pathlib import Path
import os

from environ import Env
from django.utils.translation import gettext_lazy as _

env = Env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

Env.read_env(os.path.join(BASE_DIR, '.env'))

PROJECT_NAME = "Lucarne"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG", default=False)

ALLOWED_HOSTS = env("DJANGO_ALLOWED_HOSTS").split(" ")

CSRF_TRUSTED_ORIGINS = ["https://*.lucarne-films.com", "http://*.lucarne-films.com"]

CSRF_COOKIE_DOMAIN = [".lucarne-films.com"]

# Application definition

INSTALLED_APPS = [
    "modeltranslation",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "django.contrib.sitemaps",
]

INSTALLED_APPS += [
    "directors.apps.DirectorsConfig",
    'django_admin_inline_paginator',
    "directors.templatetags.custom_tags_directors",
    "admin_ordering",
    "common",
    "sitemap"
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'directors.middlewares.WWWRedirectMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'web.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                "django.template.context_processors.i18n",
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'directors.context_processors.base_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'web.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": env("SQL_ENGINE"),
        "NAME": env("POSTGRES_DB"),
        "USER": env("POSTGRES_USER"),
        "PASSWORD": env("POSTGRES_PASSWORD"),
        "HOST": env("SQL_HOST"),
        "PORT": env("SQL_PORT"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'fr'

LANGUAGES = (
    ("fr", _("Français")),
    ("en", _("English"))
)

MODELTRANSLATION_DEFAULT_LANGUAGE = 'fr'

LOCALE_PATHS = [Path(BASE_DIR).joinpath("directors", "locale")]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_I10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = "media/"

# Static files for production

STATIC_ROOT = Path(BASE_DIR).joinpath("collectstatic")

# Media files for production

MEDIA_ROOT = Path(BASE_DIR).joinpath("media")

#MEDIA_ROOT = "/var/www/lucarnes/media/"
FILE_UPLOAD_PERMISSIONS = 0o644

# SSL proxy config
# In this tuple, when X-Forwarded-Proto is set to https the request is secure.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


AUTH_USER_MODEL = 'directors.CustomUser'

if DEBUG:
    TO_EMAIL = env("TO_EMAIL_DEBUG")
    EMAIL_HOST = 'smtp.mailtrap.io'
    EMAIL_HOST_USER = env("EMAIL_HOST_USER_DEBUG")
    EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD_DEBUG")
    EMAIL_PORT = '2525'
else:
    pass

ADMIN_URL = env("ADMIN_URL")
