# Generated by Django 4.2.9 on 2024-05-08 15:27

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Directors',
            fields=[
            ],
            options={
                'verbose_name': 'réalisateur',
                'verbose_name_plural': 'réalisateurs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('registrations.customuser',),
        ),
    ]
