# Generated by Django 4.2.9 on 2024-05-12 22:46

from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType
from django.db import migrations


def create_director_group(apps, schema_editor):
    obj, created = Group.objects.get_or_create(name="directors")
    director_content_type = ContentType.objects.get(app_label="directors", model="director")
    director_permissions = [
        "view_director",
    ]
    obj.permissions.set(Permission.objects.filter(
        content_type=director_content_type,
        codename__in=director_permissions)
    )


def delete_director_group(apps, schema_editor):
    Group.objects.filter(name="directors").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('directors', '0002_delete_directors_director'),
    ]

    operations = [
        migrations.RunPython(create_director_group, delete_director_group)
    ]
