# Generated by Django 4.2.9 on 2024-05-14 12:15

from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType
from django.db import migrations


def add_directors_permissions(apps, schema_editor):
    group = Group.objects.get(name="directors")
    director_content_type = ContentType.objects.get(app_label="videos", model="video")
    director_permissions = [
        "view_video",
        "add_video",
        "change_video",
        "delete_video"
    ]

    permission_ids = Permission.objects.filter(
        content_type=director_content_type,
        codename__in=director_permissions
    ).values_list("id", flat=True)

    group.permissions.add(*permission_ids)


def remove_directors_permission(apps, schema_editor):
    group = Group.objects.get(name="directors")
    director_content_type = ContentType.objects.get(app_label="videos", model="video")
    director_permissions = [
        "view_video",
        "add_video",
        "change_video",
        "delete_video"
    ]

    permission_ids = Permission.objects.filter(
        content_type=director_content_type,
        codename__in=director_permissions
    ).values_list("id", flat=True)

    group.permissions.remove(*permission_ids)


class Migration(migrations.Migration):

    dependencies = [
        ('directors', '0003_create_director_group'),
    ]

    operations = [
        migrations.RunPython(add_directors_permissions, remove_directors_permission)
    ]
