# Generated by Django 4.2.9 on 2024-05-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['ordering'], 'verbose_name': 'utilisateur', 'verbose_name_plural': 'utilisateurs'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='ordering',
            field=models.PositiveIntegerField(default=0, verbose_name='ordering'),
        ),
    ]
