# Generated by Django 4.2.9 on 2024-05-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='description_en',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='description_fr',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='job_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='métier'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='job_fr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='métier'),
        ),
    ]
