# Generated by Django 4.2.9 on 2024-05-13 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0004_customuser_description_en_customuser_description_fr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_director',
        ),
    ]
