# Generated by Django 4.2.9 on 2024-05-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0005_remove_customuser_is_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='default/profile_images/', null=True, upload_to='profile_images/', verbose_name='photo de profil'),
        ),
    ]
